# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4c64e497c832390d28345921b9e3f5cbdd7e129d06a69ce3a2766e7280615b9d29ef0f20ea661b5370e37bb6e433da081328569eb01fb2a4be54b1e2e388e28

test:
  secret_key_base: 74e09c3f6b54230d81682db5aa72056e0b5a9f24fdffdb88f71517b54135dd656a032183a779ac8badbdc00a37fcc6ade818ab72014209dc67e4a48903bb2b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
